### ISSUE TITLE
cf-resource using CLI v6.13 (released October 2015) - please bump CLI version

### ISSUE THREAD

**Issue by alejandrogoyen** [concourse/cf-resource#13]
Description
The current version of CLI bundled into the cf-resource container is 6.13. This older version of CLI is preventing a sample Java app from deploying successfully on PWS (repro steps for app deploy fail below).  The app binds to monitoring & log services (hostedgraphite, papertrail).

Can we update the image build process to include latest version of CLI ?

Container is using this version of CLI
6.13.0-e68ce0f-2015-10-15T22:53:58+00:00

The Latest version of CLI currently available
6.17.0+5d0be0a-2016-04-15

Repro steps
1) Clone this repo, follow setup steps (for services & PWS credentials)
https://github.com/joshlong/operationalized-applications-meetup
(you need to create file ~/.pws-operationalized.yml with your PWS credentials)

2) Load the pipeline "ci/pipeline.yml" on Concourse
fly -t lite set-pipeline -p op-apps -c ci/pipeline.yml -l ~/.pws-operationalized.yml

3) Run the pipeline, you'll get this error in the deploy stage, right after the Maven build stage
Uploading rr-php-ag...
FAILED
Error uploading application.
Server error, status code: 422, error code: 10008, message: The request is semantically invalid: must be an array.
error: Error executing cli core command
error running command: exit status 1

4) If you hijack the container and bump CLI to 6.17, the error disappears and the app is deployed successfully without issues.

**Comment by alejandrogoyen** [comment]
When running with CF_TRACE=true, CLI 6.13 sends PUT request with null payload.  They payload is non-null when using 6.17.

Here is the 6.13 output

Using route rr-php-ag.cfapps.io
Uploading rr-php-ag...

REQUEST: [2016-04-25T18:48:12Z]
PUT /v2/resource_match HTTP/1.1
Host: api.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.13.0-e68ce0f / linux

null

RESPONSE: [2016-04-25T18:48:12Z]
HTTP/1.1 422 status code 422
Content-Length: 137
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Mon, 25 Apr 2016 18:48:12 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: c2c0badc-546c-451c-5bc5-ee071cdbf3fa
X-Vcap-Request-Id: cd704f41-3606-49fd-7004-d42a0882b36e::1f675876-a210-4c02-adfa-0084d3277e76

{
  "code": 10008,
  "description": "The request is semantically invalid: must be an array.",
  "error_code": "CF-UnprocessableEntity"
}

FAILED
Error uploading application.
Server error, status code: 422, error code: 10008, message: The request is semantically invalid: must be an array.
FAILED
Error uploading application.
Server error, status code: 422, error code: 10008, message: The request is semantically invalid: must be an array.

**Comment by ihuston** [comment]
We're also having problems with the old CF cli version. We're running into [this bug](https://github.com/cloudfoundry/cli/issues/818) that was fixed in v6.17.1.

**Comment by vito** [comment]
Pretty sure this was fixed in 1.2.0. If not it'll be in 1.3.0.
