### ISSUE TITLE
Yes the cf-resource to create service

### ISSUE THREAD

**Issue by rjain-pivotal** [concourse/cf-resource#14]
Currently, the cf resource is only used to put the app (deploy)

How do I create a service and bind it to an app and then tear it down after testing ?

**Comment by vito** [comment]
That'd be a different resource. Or you could put the service in your manifest file.

**Comment by idahobean** [comment]
Hi, I've created resource for [Cloud Foundry service](https://github.com/idahobean/cf-service-resource). Could you try and feedback it?
