### ISSUE TITLE
Colour code resource based on success

### ISSUE THREAD

**Issue by srbry** [concourse/cf-resource#15]
The Git resources change to orange in the GUI when a GET fails, could the same be implemented for the CF resource when a PUT fails?

At the moment if a task has many cf resources then it is impossible to tell which CF resource had an issue without drilling down into the task.

**Comment by vito** [comment]
those are indicating different things; the color codes are only to indicate whether we're available to discover versions, not related to any jobs or builds. if a `put` failed the job should be red.
