### ISSUE TITLE
Parallel zero-downtime deployment doesn't work

### ISSUE THREAD

**Issue by mastertinner** [concourse/cf-resource#26]
In our project we're using the zero-downtime deployment functionality of this resource by stating a `current_app_name`. This fails if two deployments are happening at the same time with the error

```txt
error: Server error, status code: 400, error code: 100002, message: The app name is taken: my-app-venerable
```

I think it would make sense to add a random string to the end of the app name (e.g. `my-app-venerable-xy123`) to avoid these collisions or to be able to serialize just the deployment. Otherwise I have to serialize the whole job using https://concourse.ci/configuring-jobs.html#serial which tremendously slows down our pipeline.

**Comment by vito** [comment]
Wouldn't the next failure just be when it tries to rename the app to the `current_app_name`? I'm not sure if this is really a reasonable thing to do. Can you split just the `put` out into a separate job and serialize that? One issue with parallel deploys is if the older job finishes after the new one, your pipeline will mislead you into thinking the latest bits are there, when in reality they're not.

**Comment by mastertinner** [comment]
These are good points you are making. Thanks, @vito. In that case, we will probably use the solution you proposed and create a job just for the deployment.
