### ISSUE TITLE
Specify app route in concourse job params

### ISSUE THREAD

**Issue by dannysullivan** [concourse/cf-resource#27]
We're trying to blue-green deploy an app to multiple environments with different routes and environment variables in each environment.  The only thing preventing us from using the cf-resource is the lack of support for specifying routes in the concourse job.  As is, we can use different manifests for each environment, but it seems like overkill since there's only one difference between the environments (the route).

Looking at the code, it seems like this would involve adding an `AddRoute` method to https://github.com/concourse/cf-resource/blob/master/out/manifest.go .  I'd be happy to submit a pull request if you think this idea makes sense.

**Comment by CAFxX** [comment]
We have the same problem (for both `routes` and `stack`)

**Comment by benmoss** [comment]
This would be great, we are also trying to push an app to multiple spaces and having route conflicts

**Comment by chendrix** [comment]
I would look at a PR for this, but in general I don't think asking people to change their manifest via tasks is too big of an ask.

This could obviously end up in a combinatorial explosion where "my manifests are the same except for *X* parameter", and we end up in the same place as the old version of this resource that specified every parameter independently.
