### ISSUE TITLE
[Enhancement] Allow setting up custom startup command

### ISSUE THREAD

**Issue by r-chris** [concourse/cf-resource#45]
I was wondering if it would be possible to add the `cf push -c MYSTARTUPCMD` functionality to this resource: http://cli.cloudfoundry.org/en-US/cf/push.html

In particular I would like to be able to deploy a docker container with different startup commands. Of course I could just create individual docker containers, which is what I am currently doing, but it appears that `-c` option to add a startup command could be valuable.

_Please correct me if I'm wrong, but I didn't find a way to actually put this into the manifest file, which of course would also be a great place for it._

**Comment by vito** [comment]
Pretty sure this can be put in the manifest as `command: ...`. See https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#start-commands
