### ISSUE TITLE
CloudFoundry Zero-Downtime deployment through (community) plugins

### ISSUE THREAD

**Issue by r-chris** [concourse/cf-resource#47]
Would it be conceivable to add support for running cloud foundry (community) plugins. I'm not sure if this is the right place to add this, so please advice if not.

I am essentially trying to get continuous deployment setup for an application we are deploying via CloudFoundry through concourse.

Currently, I am using the cf-resource in concourse to push my manifest files, but it takes down the application along the way and then restarts it. What I want is to use for example [autopilot](https://github.com/contraband/autopilot) to manage the deployment so that I have zero-downtime.

**Comment by r-chris** [comment]
PS: The `cf-resource` README talks about setting `current_app_name` to do zero-downtime deployments, but I am not sure how it will actually do that?

**Comment by r-chris** [comment]
Diving deeper into this it appears that `current_app_name` is already calling `autopilot` - only that it fails with this error for me:

```

flag provided but not defined: -docker-username
Usage of zero-downtime-push:
  -f string
    	path to an application manifest
  -p string
    	path to application files
error: flag provided but not defined: -docker-username
error running command: exit status 1
```

All I added to my concourse yml was the `current_app_name: myappname`

**Comment by mjnorman** [comment]
I just went through this and there is a great tutorial at this link.  It's designed for node.js app but was able to easily modify for dotnetcore.

https://github.com/pivotalservices/concourse-pipeline-samples/blob/master/blue-green-app-deployment

**Comment by r-chris** [comment]
Thanks for the link - I have been looking for a good tutorial. From the looks of it, though, they are basically just scripting everything through tasks inside some docker containers. That's a valid way to go, but means I have to maintain a much more complex build pipeline over just being able to use something like `autopilot`.

I'll write a simple test pipeline using `current_app_name` to see if it just doesn't work when deploying docker images, but if anyone has a good example / tutorial where `current_app_name` is used successfully, don't be shy and share please!

**Comment by r-chris** [comment]
Since development appears a little bit stalled here, I might give [this pivotal cf-cli resource a shot](https://github.com/Pivotal-Field-Engineering/cf-cli-resource).

**Comment by mjnorman** [comment]
Keep in mind that autopilot deletes the old application so it's not possible to rollback as far as I can tell without another deployment.  This was good enough reason for me to go blue-green route.  Good luck!

**Comment by r-chris** [comment]
Ok thanks. As far as I understood, Autopilot renames the app, then brings up a new one and swaps them when the new one is running. I assumed they would check for success before the swap?

**Comment by mjnorman** [comment]
Well I would assume so, but was thinking more along the lines of "whoops a bug slipped into this new version" or something unexpected like that, not just that the new route is live. You might can get away with it.  If your organization doesn't require that then I'd say go for It, might be easier to attempt to change cf-resource to allow the plugin than having all the pipeline scripts for blue-green.

**Comment by r-chris** [comment]
I see where you are coming from now - there is no time with Autopilot to test-drive in production - it's take it or redeploy the old version. For our needs it should be sufficient at the moment, though.

**Comment by r-chris** [comment]
After some more research I finally realised that the `current-app-name` option already utilises the autopilot plugin for deployment, which is what I was looking for. Closing.
