### ISSUE TITLE
Allow CF_TRACE output for failed pushes

### ISSUE THREAD

**Issue by bendodd** [concourse/cf-resource#9]
During deploys to CF (especially 3rd-party provided CFs) it's useful (or required by support) to be able to provide the CF_TRACE output for debugging failed pushes

**Comment by vito** [comment]
Could this be fixed in the CLI instead somehow? Feels really gross for this low-level platform debugging feature to be needed at pretty much the top of the toolchain. Perhaps the CLI could just print request IDs when it fails?

**Comment by vito** [comment]
Closing; we won't be adding this soon, still seems like something that could be added to the CLI instead.

**Comment by datianshi** [comment]
@vito  CF_TRACE is an environment variable.... point is whether cf resource/any concourse resource accept customized environment variable
